// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCAscsYf_4ieN2zVHfO2VfnqerBbFzGj4',
    appId: '1:243352862220:web:667b5516522b96fc1ef829',
    messagingSenderId: '243352862220',
    projectId: 'fotarh-956e1',
    authDomain: 'fotarh-956e1.firebaseapp.com',
    storageBucket: 'fotarh-956e1.appspot.com',
    measurementId: 'G-DX4JDYSH0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLwsp96qbOMvvtVkFANlm8BtgBGuJP5TQ',
    appId: '1:243352862220:android:27855cb770fd9a601ef829',
    messagingSenderId: '243352862220',
    projectId: 'fotarh-956e1',
    storageBucket: 'fotarh-956e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlwW0rGUswPNgb2lxUze2vxR9GCJHsxR8',
    appId: '1:243352862220:ios:fa3be8d3335837851ef829',
    messagingSenderId: '243352862220',
    projectId: 'fotarh-956e1',
    storageBucket: 'fotarh-956e1.appspot.com',
    iosBundleId: 'com.project.fotrah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlwW0rGUswPNgb2lxUze2vxR9GCJHsxR8',
    appId: '1:243352862220:ios:457810367fb523981ef829',
    messagingSenderId: '243352862220',
    projectId: 'fotarh-956e1',
    storageBucket: 'fotarh-956e1.appspot.com',
    iosBundleId: 'com.project.fotrah.RunnerTests',
  );
}
